from __future__ import annotations

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional

from ...storage.in_memory import store
from ...domain.models.agent import Agent, AgentVersion, AgentContract, AgentCategory
from ...domain.models.base import gen_id, utc_now

router = APIRouter(prefix="/agents", tags=["agents"])


class AgentCreate(BaseModel):
    name: str
    display_name: str
    category: AgentCategory = AgentCategory.CUSTOM
    purpose: str
    role: str = ""
    model_config_id: Optional[str] = None
    skill_ids: list[str] = Field(default_factory=list)
    tool_ids: list[str] = Field(default_factory=list)
    max_turns: int = 10
    timeout_seconds: int = 300
    token_budget: int = 100000
    system_instructions: str = ""
    tenant_id: str = "tenant_forgeiq"


class AgentFactoryRequest(BaseModel):
    description: str
    category: AgentCategory = AgentCategory.CUSTOM
    tenant_id: str = "tenant_forgeiq"


@router.get("")
def list_agents(tenant_id: str = "tenant_forgeiq"):
    return store.agents.all(tenant_id)


@router.get("/{agent_id}")
def get_agent(agent_id: str):
    agent = store.agents.get(agent_id)
    if not agent:
        raise HTTPException(404, "Agent not found")
    return agent


@router.post("")
def create_agent(body: AgentCreate):
    contract = AgentContract(
        skill_ids=body.skill_ids,
        tool_ids=body.tool_ids,
        model_config_id=body.model_config_id,
        max_turns=body.max_turns,
        timeout_seconds=body.timeout_seconds,
        token_budget=body.token_budget,
    )
    agent = Agent(
        tenant_id=body.tenant_id,
        id=gen_id("agent_"),
        name=body.name.lower().replace(" ", "-"),
        display_name=body.display_name,
        category=body.category,
        purpose=body.purpose,
        role=body.role,
        model_config_id=body.model_config_id,
        skill_ids=body.skill_ids,
        tool_ids=body.tool_ids,
        max_turns=body.max_turns,
        timeout_seconds=body.timeout_seconds,
        token_budget=body.token_budget,
        contract=contract,
        system_instructions=body.system_instructions or f"You are a {body.display_name}. {body.purpose}",
        published=False,
        current_version="v1",
        created_at=utc_now(),
    )
    v1 = AgentVersion(
        tenant_id=body.tenant_id,
        id=gen_id("aver_"),
        agent_id=agent.id,
        version="v1",
        published=False,
        is_default=True,
        contract=contract,
        system_instructions=agent.system_instructions,
        changelog="Initial version",
        created_at=utc_now(),
    )
    agent.versions = [v1]
    store.agents.add(agent)
    return agent


@router.post("/factory")
def agent_factory(body: AgentFactoryRequest):
    category = body.category
    name = body.description[:40].strip()
    display_name = name.title()

    relevant_skills = []
    for s in store.skills.all(body.tenant_id):
        if any(kw in body.description.lower() for kw in [s.language.lower(), s.framework.lower()] if kw):
            relevant_skills.append(s.id)

    relevant_tools = []
    for t in store.tools.all(body.tenant_id):
        if any(kw in body.description.lower() for kw in [t.name, t.display_name.lower()]):
            relevant_tools.append(t.id)

    models = store.models.all(body.tenant_id)
    model_id = models[0].id if models else None

    contract = AgentContract(
        skill_ids=relevant_skills[:3],
        tool_ids=relevant_tools[:3],
        model_config_id=model_id,
        max_turns=15,
        timeout_seconds=600,
        token_budget=200000,
    )

    agent = Agent(
        tenant_id=body.tenant_id,
        id=gen_id("agent_"),
        name=display_name.lower().replace(" ", "-"),
        display_name=display_name,
        category=category,
        purpose=body.description,
        role="Generated Agent",
        model_config_id=model_id,
        skill_ids=relevant_skills[:3],
        tool_ids=relevant_tools[:3],
        contract=contract,
        system_instructions=f"You are a {display_name}. {body.description} Always produce evidence of your work.",
        published=True,
        current_version="v1",
        created_at=utc_now(),
    )
    v1 = AgentVersion(
        tenant_id=body.tenant_id,
        id=gen_id("aver_"),
        agent_id=agent.id,
        version="v1",
        published=True,
        is_default=True,
        contract=contract,
        system_instructions=agent.system_instructions,
        changelog="Generated by Agent Factory",
        created_at=utc_now(),
    )
    agent.versions = [v1]
    store.agents.add(agent)
    return agent


@router.get("/{agent_id}/versions")
def get_agent_versions(agent_id: str):
    agent = store.agents.get(agent_id)
    if not agent:
        raise HTTPException(404, "Agent not found")
    return agent.versions


@router.post("/{agent_id}/versions")
def create_agent_version(agent_id: str, changelog: str = "New version"):
    agent = store.agents.get(agent_id)
    if not agent:
        raise HTTPException(404, "Agent not found")
    version_num = len(agent.versions) + 1
    new_version = AgentVersion(
        tenant_id=agent.tenant_id,
        id=gen_id("aver_"),
        agent_id=agent_id,
        version=f"v{version_num}",
        published=False,
        is_default=False,
        contract=agent.contract,
        system_instructions=agent.system_instructions,
        changelog=changelog,
        created_at=utc_now(),
    )
    agent.versions.append(new_version)
    return new_version


@router.post("/{agent_id}/publish/{version}")
def publish_agent_version(agent_id: str, version: str):
    agent = store.agents.get(agent_id)
    if not agent:
        raise HTTPException(404, "Agent not found")
    for v in agent.versions:
        if v.version == version:
            v.published = True
            v.is_default = True
            agent.current_version = version
            agent.published = True
        else:
            v.is_default = False
    return agent
